---
version: '2'
services:
    # https://haugene.github.io/docker-transmission-openvpn/run-from-docker-registry/
    jackett-transmission-openvpn:
      image: haugene/transmission-openvpn
      container_name: transmission-openvpn
      volumes:
          - '/your/data:/data'
          - '/etc/localtime:/etc/localtime:ro'
      environment:
          - PUID=1000
          - PGID=1000
          - CREATE_TUN_DEVICE=true
          - OPENVPN_PROVIDER=PIA
          - OPENVPN_CONFIG=CA\
          - OPENVPN_USERNAME=username
          - OPENVPN_PASSWORD=password
          - WEBPROXY_ENABLED=false
          - LOCAL_NETWORK=192.168.0.0/16
      logging:
          driver: json-file
          options:
            max-size: 10m
      ports:
          - '9091:9091'
      restart: unless-stopped
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
      volumes:
        - /your/data:/config
        - /your/downloads:/downloads
      ports:
        - 9117:9117
      restart: unless-stopped
